---
# Source: generic/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: generic-config
  namespace: default
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
---
# Source: generic/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: generic
  namespace: default
  labels:
    helm.sh/chart: myrelease-generic
    app.kubernetes.io/name: generic
    app.kubernetes.io/instance: myrelease
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
  - name: generic
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: generic
    app.kubernetes.io/instance: myrelease
---
# Source: generic/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: generic
  namespace: default
  labels:
    helm.sh/chart: myrelease-generic
    app.kubernetes.io/name: generic
    app.kubernetes.io/instance: myrelease
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm 
spec: 
  replicas: 2
  selectors: 
    matchLabels: 
      
      app.kubernetes.io/name: generic
      app.kubernetes.io/instance: myrelease
  template:
    metadata:
    helm.sh/chart: myrelease-generic
    app.kubernetes.io/name: generic
    app.kubernetes.io/instance: myrelease
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm 
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - my-app
              topologyKey:  kubernetes.io/hostname
            weight: 100

        containers:
          - name: generic
            image: my-docker-repo/my-app:latest
            imagePullPolicy: IfNotPresent
            workingDir: /app
---
# Source: generic/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: generic-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: generic-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
---
# Source: generic/templates/statefulsets.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: generic
  namespace: default
  labels:
    helm.sh/chart: myrelease-generic
    app.kubernetes.io/name: generic
    app.kubernetes.io/instance: myrelease
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 
  selector:
    matchLabels:
      
      app.kubernetes.io/name: generic
      app.kubernetes.io/instance: myrelease
  template:
    metadata:
      labels:
        helm.sh/chart: myrelease-generic
        app.kubernetes.io/name: generic
        app.kubernetes.io/instance: myrelease
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - my-app
                topologyKey: kubernetes.io/hostname
              weight: 100

      containers:
        - name: generic
          image: my-docker-repo/my-app:latest
          imagePullPolicy: IfNotPresent
          workingDir: /app
          ports:
            - containerPort: 8080
              name: generic
          envFrom:
            - configMapRef:
                name: generic-config
            - secretRef:
                name: generic-secret
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - mountPath: /data
              name: data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: standard
        resources:
          requests:
            storage: 5Gi
---
# Source: generic/templates/secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: generic-secret
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: my-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: generic-secret
  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: my-secret-key
      version: latest
      property: password
  - secretKey: API_KEY
    remoteRef:
      key: my-secret-key
      version: latest
      property: apiKey
