{{- if and .Values.service (not .Values.rollout) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol | default "TCP" }}
      targetPort: {{ .targetPort }}
    {{- end }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
{{- end }}
